### ISSUE TITLE
configure LOGGING

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/semgrep-rules#122]

**Comment by DrewDennison** [comment]
@jacobian can you provide more details here or link to a best practices guide you had in mind? Thanks!

**Comment by jacobian** [comment]
Without a configuration for `settings.LOGGING`, your own logs (through the `logging` package) don't show up anywhere. So a project needs to [configure logging](https://docs.djangoproject.com/en/3.0/topics/logging/#configuring-logging) -- this bites me all the time.

That said, I'm not sure this makes a great check; it's pretty low-value.
