### ISSUE TITLE
app should be injected with context processor (current_app)

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/semgrep-rules#148]

**Comment by ulziibay** [comment]
This check is confusingly worded. @DrewDennison @minusworld  can you clarify what it is saying!

**Comment by mschwager** [comment]
I'm also confused at what this is getting at. Could you provide an example?

**Comment by DrewDennison** [comment]
Not sure the title is right anymore I believe it's been copied 2-3 times between spreadsheets but here is an article I remember reading a long time ago when we came up with the check https://hackingandslacking.com/demystifying-flasks-application-context-c7bd31a53817?gi=b173c62a9e

**Comment by DrewDennison** [comment]
https://flask.palletsprojects.com/en/1.0.x/appcontext/#purpose-of-the-context

**Comment by DrewDennison** [comment]
might be a dup of #166
