### ISSUE TITLE
Mutual dependency between sgrep and sgrep-rules CI

### ISSUE THREAD

**Issue by aryx** [returntocorp/semgrep-rules#287]
**Describe the bug**
I have a fix to sgrep that fixes a regression in sgrep-rules, but I can't push either because they are mutually dependent (CI for sgrep refuses because sgrep-rules has the regression, but the fix in sgrep-rules refuses because it still uses the old sgrep). 

**To Reproduce**

See the failure in sgrep CI at https://github.com/returntocorp/sgrep/pull/346/checks
See the failure in sgrep-rules CI at https://github.com/returntocorp/sgrep-rules/pull/286/checks

**Expected behavior**
If a //todoruleid: suddenly starts to PASS, we should be happy instead of making the CI fails.

**Comment by nbrahms** [comment]
@DrewDennison AFAICT, the `--test-ignore-todo` flag isn't wired up to anything in `sgrep.py` (in returntocorp/sgrep).

**Comment by aryx** [comment]
update: I actually managed to push to sgrep-rules/ because probably sgrep-docker-build managed to push a new version even though the github action of my PR did not run. 
So that's a way to break the mutual dependency ... you force-push in sgrep, wait 1h that sgrep-docker-build push a new dockerimage and then you can modify sgrep-rules.

**Comment by aryx** [comment]
Same problem here: https://github.com/returntocorp/sgrep/pull/432/checks?check_run_id=577287877

**Comment by aryx** [comment]
Some of the tests had some // todoruleid: 
that was now working! Really if the test fails because of new error and the error is a // todoruleid
then the test should not fail! it should be happy instead! Of course we need to fix those and
change them from todoruleid to regular ruleid:, but it would be better to have another mechanism that test failure in CI to force me to modify sgrep-rules.

**Comment by aryx** [comment]
Another one: https://github.com/returntocorp/sgrep-rules/pull/330
