### ISSUE TITLE
[Check] Java: Overly permissive file permissions

### ISSUE THREAD

**Issue by minusworld** [returntocorp/semgrep-rules#433]
**Check Description**
Alert when files are world-anything-able.

cf. https://find-sec-bugs.github.io/bugs.htm#OVERLY_PERMISSIVE_FILE_PERMISSION

- [x] This ticket has links, references, or examples.
- [x] Your check has true positive and true negative test cases.
- [x] Your check has been labeled with true positive and false positive findings on at least 10 repositories, and the link is pasted in the ticket. If there are no findings, paste the triager link anyway.
- [x] Your check PR has been reviewed and merged.
Now, close the ticket!

**Comment by inkz** [comment]
blocked by https://github.com/returntocorp/semgrep/issues/733

**Comment by inkz** [comment]
https://dev.massive.ret2.co/jobs/1053
