### ISSUE TITLE
[Check] Java: CORS wildcard

### ISSUE THREAD

**Issue by minusworld** [returntocorp/semgrep-rules#457]
**Check Description**

cf. https://find-sec-bugs.github.io/bugs.htm#PERMISSIVE_CORS

- [x] This ticket has links, references, or examples.
- [x] Your check has true positive and true negative test cases.
- [x] Your check has been labeled with true positive and false positive findings on at least 10 repositories, and the link is pasted in the ticket. If there are no findings, paste the triager link anyway.
- [x] Your check PR has been reviewed and merged.
Now, close the ticket!

**Comment by inkz** [comment]
code examples:
https://www.baeldung.com/spring-response-header
https://www.programcreek.com/java-api-examples/?class=javax.servlet.http.HttpServletResponse&method=addHeader

**Comment by inkz** [comment]
blocked by https://github.com/returntocorp/semgrep/issues/743
the issue itself is resolved, waiting for semgrep update

**Comment by inkz** [comment]
unblocked

**Comment by inkz** [comment]
https://dev.massive.ret2.co/triager/filter/1038
