### ISSUE TITLE
Regexp support

### ISSUE THREAD

**Issue by javixeneize** [returntocorp/semgrep-rules#484]
Hi

Im trying to create a very simple rule to validate if there is a hardcoded password in the code, just trying to find a hardcoded password in the code

How should i configure the pattern to be able to use a regexp? All the examples i have seen are searching for a specific string or a variable configuration but i have seen no examples to use regexp

Thanks

**Comment by clintgibler** [comment]
Hey @javixeneize, thanks for reaching out! Happy to help :)

Just to make sure I understand where you're coming from:

Are you looking for hardcoded passwords to specific API calls that you know ahead of time? 
* If so, you could use something like `some_method("...")` which will find when `some_method` is called with a hardcoded string as the first argument. 
* See here for an example of finding function calls with string literals (secrets) as arguments: https://semgrep.live/2Gq

Do you know what the secret looks like? (e.g. AWS keys starting with `AKIA...`)
* We're working on having an additional clause `pattern-regex` that allows you to simply search file contents by regex string. It's not quite released yet, but should be in the next week or two.

Alternatively, you can use `pattern-where-python` to introspect on the value of a metavariable you've matched. See here for an example:
* https://github.com/returntocorp/semgrep-rules/blob/develop/go/lang/security/audit/crypto/use_of_weak_rsa_key.go
* https://github.com/returntocorp/semgrep-rules/blob/develop/go/lang/security/audit/crypto/use_of_weak_rsa_key.yaml

More info on `pattern-where-python`: https://github.com/returntocorp/semgrep/blob/develop/docs/configuration-files.md#pattern-where-python

Does this help? Let me know if there's any other info or help I can provide.

Thanks for using semgrep! 🎉

**Comment by DrewDennison** [comment]
@javixeneize 👍 to what @clintgibler said above. If you want to use regexes they are available for strings such as `callThing("=~/foo.*/",...)` see https://semgrep.live/jbl for a live example and more details in the [pattern docs](https://github.com/returntocorp/semgrep/blob/develop/docs/pattern-features.md#strings).

Also as Clint mentioned we're working on `pattern-regex` so you can compose with semgrep patterns or even just run regex as pre-filter. Happy to help if you have questions and would love your feedback on what's easy and difficult to understand 🙏 cc @mschwager who is building `pattern-regex` this week.

**Comment by javixeneize** [comment]
Thanks both. It is to find hardcoded passwords in the code, so pattern-regex will make it :)
Something like String password = '1234';

Once it is ready, i will check if it solves my problem
Thanks for the clear explanation!

**Comment by DrewDennison** [comment]
Ah so if I understand you want to match the left hand side of the expression with a regex - got it. I usually do it like https://semgrep.live/yBO

**Comment by javixeneize** [comment]
that example would help. Thanks!

**Comment by javixeneize** [comment]
Hi

I checked that example and its not exactly what i needed, but im sure the pattern-regexp will make it work.

Can you answer to this issue once it is released please?
Thanks

**Comment by clintgibler** [comment]
Hi @javixeneize! 

Hope you've been well, sorry for the response delay. 

`pattern-regex` has been released in semgrep [v0.8.0](https://github.com/returntocorp/semgrep/releases/tag/v0.8.0), and you can see the docs [here](https://github.com/returntocorp/semgrep/blob/v0.8.0/docs/configuration-files.md#pattern-regex).

Give it a try, and let me know if you have any issues :)

Have a great weekend!

**Comment by javixeneize** [comment]
Thanks Clint. Is this avaliable via brew?

Thanks

**Comment by javixeneize** [comment]
Hi

I tested it in the docker image, which is 0.8.1 with the following regex:

rules:
  - id: hardcoded password
    pattern-regex: (?i)^.*password.*$
    message: "Hardcoded password"
    languages: [python]
    severity: ERROR

  - id: eqeq-is-bad
    pattern: $X == $X
    message: "$X == $X is a useless equality check"
    languages: [python]
    severity: ERROR



My code is as follows:

def test():
    password = 'test'
    print (password)

def get_node(node_id, nodes):
    for node in nodes:
        if node.id == node.id:  # Oops, supposed to be 'node_id'
            return node
    return None


Im calling the docker image like this:

docker run --rm -v "${PWD}:/home/repo" returntocorp/semgrep --config rules_test.yml being rules_test the yml that contains the rule above

It only reports the eqeq-is-bad rule, when i was expecting it to report both issues

ERROR rule:eqeq-is-bad: node.id == node.id is a useless equality check
7:        if node.id == node.id:  # Oops, supposed to be 'node_id'

How should i set the rexep?

Thanks

**Comment by DrewDennison** [comment]
@mschwager @clintgibler tagging here

**Comment by brendongo** [comment]
I don't think regex rule `(?i)^.password.$` matches anything in the code file. You either want to turn multi line mode on and add some kleene stars:`(?im)^.*password.*$` (https://semgrep.live/ZqgD for convenience) or really this is equivalent to just matching the regex `(?i)password` (https://semgrep.live/nJJX for convenience) no?

**Comment by brendongo** [comment]
>Thanks Clint. Is this avaliable via brew?

Yes it is. `brew install returntocorp/semgrep/semgrep`

**Comment by mschwager** [comment]
> You either want to turn multi line mode on and add some kleene stars: (?im)^.*password.*$ (https://semgrep.live/ZqgD for convenience) or really this is equivalent to just matching the regex (?i)password (https://semgrep.live/nJJX for convenience

Yup, this was going to be my suggestion!

If you're looking for something that only matches setting a password variable using the multiline flag you could do something like:

```
$ cat test.py 
def test():
    password = 'test'
    print(password)
```

```yaml
$ cat conf.yaml 
rules:
- id: hardcoded password
  pattern-regex: (?im)^\s*password =.*$
  message: "Hardcoded password"
  languages: [python]
  severity: ERROR
```

```
$ semgrep --config conf.yaml test.py 
test.py
ERROR rule:hardcoded password: Hardcoded password
2:    password = 'test'
```

But then again, you could just use the standard `pattern` operator at that point:

```yaml
rules:
- id: hardcoded password
  pattern: password = "..."
  message: "Hardcoded password"
  languages: [python]
  severity: ERROR
```

If you're looking for any usage of the string 'password', then @brendongo's suggestion of `(?i)password` should work :+1: 

Hope this helps!

**Comment by javixeneize** [comment]
Apologies, i copied the wrong regex. It is     

pattern-regex: '(?i)^.*password.*$'

I think this regex is valid and should match with the value i have in my test file. 

Thanks

**Comment by mschwager** [comment]
Do you mean you're using `pattern-regex: '(?i)^.*password.*$'`? It looks like `password` keeps getting italicized, so you must be including a `_` or `*` and Github is rendering it as italicized.

I think I see the problem. If you're using `'(?i)^.*password.*$'` then you either have to drop the `^` and `$`, or use [multiline mode](https://docs.python.org/3/library/re.html#re.MULTILINE). Both of the following work for me with your test code:

* `'(?i).*password.*'`
* `'(?im)^.*password.*$'`

**Comment by javixeneize** [comment]
Hi

It only works with (?im) modifier. With (?i) it doesnt work for me in the version im using via docker

**Comment by mschwager** [comment]
Hi @javixeneize,

Please update to the latest version of `semgrep` in Docker by running the following command:

```
$ docker pull returntocorp/semgrep:latest
```

Using the latest version (`0.9.0`) the `'(?i).*password.*'` expression works for me:

```
$ docker run returntocorp/semgrep:latest --version
0.9.0
```

```
$ cat test.py 
def test():
    password = 'test'
    print(password)
```

```
$ cat test.yaml 
rules:
- id: hardcoded password
  pattern-regex: '(?i).*password.*'
  message: "Hardcoded password"
  languages: [python]
  severity: ERROR
```

```
$ docker run --rm -v "${PWD}:/home/repo" returntocorp/semgrep:latest --config test.yaml test.py
test.py
ERROR rule:hardcoded password: Hardcoded password
2:    password = 'test'
3:    print(password)
```

Can you confirm?

**Comment by javixeneize** [comment]
Hi

Yes, it works with that regexp.

It works with:

- '(?i).*password.*'
- '(?im)^.*password.*$'

But doesnt with 

-  '(?i)^.*password.*'

I believe that regexp is also valid, isnt it? You mentioned using re.multiline, but i understand its something that should be done inside your tool when you analyse the regex, isnt it?

Thanks

**Comment by mschwager** [comment]
> You mentioned using re.multiline, but i understand its something that should be done inside your tool when you analyse the regex, isnt it?

Not necessarily. These flags are available to use inline in `pattern-regex` with the `(?...)` specification, e.g. `(?i)`.

> But doesnt with `'(?i)^.*password.*'`

If you need to use `^` or `$` then you'll have to use multi-line mode. The following regex works for me: `'(?im)^.*password.*'`.

> Yes, it works with that regexp.

I'm glad we got a working solution for you! I'm going to close this out. Let us know if you have any other questions!
