### ISSUE TITLE
[Check] Insecure Deserialization checks for Golang

### ISSUE THREAD

**Issue by minusworld** [returntocorp/semgrep-rules#514]
**Check Description**
Set of checks for insecure deserialization in Golang.
Target frameworks:

- [x] Lang
- [x] Gorilla --- no checks identified
- [x] GORM --- no checks identified
- [x] gRPC

**Comment by minusworld** [comment]
Lang:
- https://github.com/returntocorp/semgrep-rules/issues/518

**Comment by minusworld** [comment]
gRPC checks:

* https://github.com/returntocorp/semgrep-rules/pull/550
* https://github.com/returntocorp/semgrep-rules/pull/549

**Comment by minusworld** [comment]
Nothing readily identifiable for GORM or Gorilla. Closing.

**Comment by caioluders** [comment]
@c3l3si4n told me that deser on golang does not exists
