### ISSUE TITLE
[Check] C: strcopy blacklist rule 

### ISSUE THREAD

**Issue by ulziibay** [returntocorp/semgrep-rules#523]
**Check Description**

- [ ] This ticket has links, references, or examples.
- [ ] Your check has true positive and true negative test cases.
- [ ] Your check has been labeled with true positive and false positive findings on at least 10 repositories, and the link is pasted in the ticket. If there are no findings, paste the triager link anyway.
- [ ] Your check PR has been reviewed and merged.
Now, close the ticket!

**Comment by mschwager** [comment]
We have this rule: https://github.com/returntocorp/semgrep-rules/blob/develop/c/lang/security/insecure-use-string-copy-fn.yaml :tada:
