### ISSUE TITLE
avoid {% autoescape off %}, safe/safeseq filter

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/semgrep-rules#78]

**Comment by minusworld** [comment]
https://github.com/returntocorp/semgrep-rules/blob/develop/python/jinja2/security/audit/autoescape-disabled.yaml
https://github.com/returntocorp/semgrep-rules/blob/2b733c58f4daea4cb72f2694f9903a62c0fcddda/python/django/security/audit/xss/template-var-unescaped-with-safeseq.html
